### ISSUE TITLE
Deepnight library

### ISSUE THREAD

**Issue by Yann-P** [deepnight/ld43-saveAndSacrifices#1]
Hi,
would you would be willing to share your mt.deepnight.Lib library or is it private?

Thanks!

**Comment by Yann-P** [comment]
Solved with open sourcing of https://github.com/deepnight/deepnightLibs
Many thanks!

**Comment by deepnight** [comment]
Sorry it took that much time :) I'm updating all repos to get rid of unavailable external dependencies.
